# Generated by Django 5.0.2 on 2024-02-12 11:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('job_1', models.CharField(max_length=25)),
                ('job_2', models.CharField(blank=True, max_length=25)),
                ('job_3', models.CharField(blank=True, max_length=25)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone_1', models.IntegerField()),
                ('phone_2', models.IntegerField(blank=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=50)),
                ('avilable', models.BooleanField()),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instgram', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='profile')),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('present', models.BooleanField()),
                ('graduate_date', models.DateField(blank=True)),
                ('certifcate', models.ImageField(upload_to='courses')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('present', models.BooleanField()),
                ('graduate_date', models.DateField(blank=True)),
                ('certifcate', models.ImageField(upload_to='education')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('present', models.BooleanField()),
                ('end_date', models.DateField(blank=True)),
                ('certifcate', models.ImageField(upload_to='courses')),
                ('responsiblity_1', models.CharField(max_length=200)),
                ('responsiblity_2', models.CharField(blank=True, max_length=200)),
                ('responsiblity_3', models.CharField(blank=True, max_length=200)),
                ('responsiblity_4', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('emoji', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('emoji', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rate must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rate cannot be greater than 5.')])),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('link', models.URLField()),
                ('image_1', models.ImageField(upload_to='projects')),
                ('image_2', models.ImageField(upload_to='projects')),
                ('image_3', models.ImageField(upload_to='projects')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
    ]
