# Generated by Django 5.0.2 on 2024-02-15 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rate must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rate cannot be greater than 100.')]),
        ),
    ]
